// apps/web/src/routes/spiele/+page.svelte
<script lang="ts">
    import { Accordion } from "bits-ui";
    import { ChevronDownIcon } from "@lucide/svelte";

    import { cn, formatDate } from "$lib/utils";
    import type { PageProps } from "./$types";

    const { data }: PageProps = $props();

    const championship = $derived(data.championship);
    const rounds = $derived(data.roundsData);

    const itemClass = cn(
        "group bg-surface border-surface border-y",
        "xs:rounded-md xs:border",
        "transition-[margin] duration-300 ease-out",
        "data-[state=open]:my-2 first:data-[state=open]:mt-0 last:data-[state=open]:mb-0",
    );

    const triggerClass = cn(
        "flex w-full cursor-pointer select-none items-center justify-between",
        "px-2 py-3 xs:px-4 xs:rounded-md",
        "outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-focus",
    );

    const contentClass = cn(
        "overflow-hidden border-t border-input",
        "px-2 py-2 xs:px-4",
        "data-[state=open]:animate-accordion-down data-[state=closed]:animate-accordion-up",
    );

    const thClass = cn("text-subtle pt-2 pb-3 text-xs font-medium tracking-wide uppercase");
    const tdClass = cn("w-px py-3 px-1 xs:px-2 tabular-nums");

    const matchLinkClass = cn(
        "rounded outline-none",
        "focus-visible:ring-2 focus-visible:ring-offset-4 focus-visible:ring-offset-surface focus-visible:ring-focus",
    );
</script>

<svelte:head>
    <title>Spiele · {championship.name}</title>
</svelte:head>

<div class="mx-auto w-full max-w-5xl py-8">
    <div class="xs:px-0 mb-6 flex flex-col items-center gap-2 px-4">
        <h1 class="text-2xl font-semibold tracking-tight">Spielübersicht</h1>
        <p class="text-subtle text-sm">{championship.name}</p>
    </div>

    {#if rounds.length === 0}
        <p class="text-subtle px-4 text-sm">Noch keine Runden gespielt.</p>
    {:else}
        <Accordion.Root
            type="single"
            value={String(data.defaultOpenRound)}
            class="flex flex-col gap-0.5"
        >
            {#each rounds as round (round.nr)}
                {@const matchesWithResult = round.matches.filter((m) => m.result !== null).length}

                {@const totalMatches = round.matches.length}
                {@const roundSpiele =
                    matchesWithResult === totalMatches
                        ? `${totalMatches}`
                        : `${matchesWithResult}/${totalMatches}`}

                <Accordion.Item value={String(round.nr)} class={itemClass}>
                    <Accordion.Trigger class={triggerClass}>
                        <span class="text-sm font-medium">Runde {round.nr}</span>
                        <span class="flex items-center gap-3">
                            <span class="text-subtle text-xs">{roundSpiele} Sp.</span>
                            <ChevronDownIcon
                                size={14}
                                class="text-subtle transition-transform duration-200 group-data-[state=open]:rotate-180"
                            />
                        </span>
                    </Accordion.Trigger>
                    <Accordion.Content class={contentClass}>
                        <table class="w-full text-sm">
                            <thead>
                                <tr class="border-input border-b text-left">
                                    <th class={cn(thClass, "w-px px-1 xs:px-2 text-right")}>#</th>
                                    <th class={cn(thClass, "hidden xs:table-cell w-px px-2")}>
                                        Datum
                                    </th>
                                    <th class={cn(thClass, "hidden sm:table-cell w-px px-2 whitespace-nowrap")}>
                                        Liga
                                    </th>
                                    <th class={cn(thClass, "px-1 xs:px-2")}>Paarung</th>
                                    <th class={cn(thClass, "w-px px-1 xs:px-2 text-center")}>
                                        Erg.
                                    </th>
                                    <th class={cn(thClass, "w-px px-1 xs:px-2 text-right")}>
                                        Pkt
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {#each round.matches as match (match.nr)}
                                    <tr class="border-input border-b last:border-b-0">
                                        <td class={cn(tdClass, "text-right")}>
                                            <a
                                                href="/spiele/{match.nr}"
                                                class={cn(
                                                    matchLinkClass,
                                                    "text-subtle hover:text-base transition-colors",
                                                )}
                                            >
                                                {match.nr}
                                            </a>
                                        </td>
                                        <td
                                            class="hidden xs:table-cell w-px px-2 py-3 tabular-nums"
                                        >
                                            {match.date ? formatDate(match.date) : "–"}
                                        </td>
                                        <td
                                            class="hidden sm:table-cell w-px px-2 py-3 text-subtle text-xs whitespace-nowrap"
                                        >
                                            {match.liga ?? "–"}
                                        </td>
                                        <td class="px-1 py-3 xs:px-2">
                                            <a href="/spiele/{match.nr}" class={matchLinkClass}>
                                                <span class="hidden sm:inline"
                                                    >{match.paarung}</span
                                                >
                                                <span class="sm:hidden">{match.paarungShort}</span>
                                            </a>
                                        </td>
                                        <td class={cn(tdClass, "text-center")}>
                                            {match.result ?? "–:–"}
                                        </td>
                                        <td class={cn(tdClass, "text-right")}>
                                            {match.points !== null ? match.points : "–"}
                                        </td>
                                    </tr>
                                {/each}
                            </tbody>
                        </table>
                    </Accordion.Content>
                </Accordion.Item>
            {/each}
        </Accordion.Root>
    {/if}
</div>

// apps/web/src/routes/_championship/spiele.tsx
import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";

import { RoundAccordion } from "#/components/round-accordion.tsx";
import { formatDate } from "#/lib/format.ts";
import { roundsQueryOptions } from "#/lib/spiele.ts";
import type { SpieleRound } from "#/lib/spiele.ts";

export const Route = createFileRoute("/_championship/spiele")({
  loader: ({ context }) => {
    const id = context.championship?.id;
    if (id !== undefined) {
      return context.queryClient.ensureQueryData(roundsQueryOptions(id));
    }
  },
  component: RouteComponent,
});

function RouteComponent() {
  const { championship } = Route.useRouteContext();

  if (!championship) {
    return (
      <div className="mx-auto w-full max-w-5xl py-8">
        <p className="text-subtle py-16 text-center text-base">Kein aktives Turnier.</p>
      </div>
    );
  }

  return <SpieleView championshipId={championship.id} championshipName={championship.name} />;
}

function SpieleView({
  championshipId,
  championshipName,
}: {
  championshipId: number;
  championshipName: string;
}) {
  const {
    data: { rounds },
  } = useSuspenseQuery(roundsQueryOptions(championshipId));

  const lastResultIndex = rounds.findLastIndex((r) => r.matches.some((m) => m.result !== null));
  const defaultOpenIndex = lastResultIndex >= 0 ? lastResultIndex : 0;

  return (
    <div className="mx-auto w-full max-w-5xl py-8">
      <div className="xs:px-0 mb-6 flex flex-col items-center gap-2 px-4">
        <h1 className="text-2xl font-semibold tracking-tight">Spielübersicht</h1>
        <p className="text-subtle text-sm">{championshipName}</p>
      </div>

      {rounds.length === 0 ? (
        <p className="text-subtle px-4 text-base">Noch keine Runden gespielt.</p>
      ) : (
        <div className="border-subtle border-t">
          {rounds.map((round, i) => (
            <SpieleRoundItem key={round.nr} round={round} defaultOpen={i === defaultOpenIndex} />
          ))}
        </div>
      )}
    </div>
  );
}

function SpieleRoundItem({ round, defaultOpen }: { round: SpieleRound; defaultOpen: boolean }) {
  const matchesWithResult = round.matches.filter((m) => m.result !== null).length;
  const totalMatches = round.matches.length;
  const roundSpiele =
    matchesWithResult === totalMatches ? `${totalMatches}` : `${matchesWithResult}/${totalMatches}`;

  return (
    <RoundAccordion
      title={`Runde ${round.nr}`}
      defaultOpen={defaultOpen}
      meta={<span className="text-subtle text-xs">{roundSpiele} Sp.</span>}
    >
      <table className="w-full text-base">
        <thead>
          <tr className="border-subtle text-muted border-b text-left text-xs tracking-wide uppercase">
            <th className="xs:px-2 w-px px-1 pt-2 pb-3 text-right font-medium">#</th>
            <th className="xs:table-cell hidden w-px px-2 pt-2 pb-3 font-medium">Datum</th>
            <th className="hidden w-px px-2 pt-2 pb-3 font-medium whitespace-nowrap sm:table-cell">
              Liga
            </th>
            <th className="xs:px-2 px-1 pt-2 pb-3 font-medium">Paarung</th>
            <th className="xs:px-2 w-px px-1 pt-2 pb-3 text-center font-medium">Erg.</th>
            <th className="xs:px-2 w-px px-1 pt-2 pb-3 text-right font-medium">Pkt</th>
          </tr>
        </thead>
        <tbody>
          {round.matches.map((match) => (
            <tr key={match.id} className="border-subtle border-b last:border-b-0">
              <td className="text-subtle xs:px-2 w-px px-1 py-3 text-right tabular-nums">
                {match.nr}
              </td>
              <td className="xs:table-cell hidden w-px px-2 py-3 tabular-nums">
                {match.date ? formatDate(match.date) : "–"}
              </td>
              <td className="text-subtle hidden w-px px-2 py-3 text-xs whitespace-nowrap sm:table-cell">
                {match.liga ?? "–"}
              </td>
              <td className="xs:px-2 px-1 py-3">
                <span className="hidden sm:inline">{match.paarung}</span>
                <span className="sm:hidden">{match.paarungShort}</span>
              </td>
              <td className="xs:px-2 w-px px-1 py-3 text-center tabular-nums">
                {match.result ?? "–:–"}
              </td>
              <td className="xs:px-2 w-px px-1 py-3 text-right tabular-nums">
                {match.points ?? "–"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </RoundAccordion>
  );
}
