// apps/web-legacy/src/routes/login/+page.svelte
<script lang="ts">
    import {
        Checkbox,
        PinInput,
        REGEXP_ONLY_DIGITS,
        type PinInputRootSnippetProps,
    } from "bits-ui";
    import { cn } from "$lib/utils";
    import type { PageData, ActionData } from "./$types";
    import { CheckIcon } from "@lucide/svelte";
    type CellProps = PinInputRootSnippetProps["cells"][0];

    const { data, form }: { data: PageData; form: ActionData } = $props();
    let step = $derived(form?.step ?? data.step);
    let email = $derived(form?.email ?? data.email);

    const inputClass = cn(
        "w-full rounded-md border border-input bg-base px-3 py-2",
        "text-sm text-base placeholder:text-subtle",
        "outline-none transition",
        "focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface",
    );

    const btnClass = cn(
        "rounded-lg px-4 py-2.5 text-sm font-medium outline-none transition",
        "active:scale-[0.98] focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface",
    );

    const btnPrimaryClass = cn(btnClass, "bg-accent hover:bg-accent-hovered text-white");

    const btnSecondaryClass = cn(btnClass, "border border-input bg-surface hover:bg-subtle text-base");

    const checkboxClass = cn(
        "flex size-5 items-center justify-center rounded border border-input",
        "outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface",
        "data-[state=checked]:bg-accent",
    );

    const pinCellClass = cn(
        "relative h-14 w-10 text-[2rem] text-base",
        "border-input border-y border-r first:rounded-l-md first:border-l last:rounded-r-md",
    );
</script>

<svelte:head>
    <title>Anmelden · runde.tips</title>
</svelte:head>

<div class="flex flex-1 items-center justify-center px-4 py-12">
    <div
        class="border-surface bg-surface flex w-full max-w-lg flex-col gap-6 rounded-xl border p-8"
    >
        <h1 class="text-2xl font-medium text-center">Anmeldung</h1>
        {#if step === "email"}
            <form
                method="POST"
                action="?/requestCode"
                class="flex flex-col gap-4 items-center"
            >
                <label class="flex flex-col gap-1.5 w-full">
                    <span class="text-sm font-medium">E-Mail</span>
                    <input
                        value={email}
                        type="email"
                        name="email"
                        required
                        placeholder="deine@email.de"
                        autocomplete="email"
                        class={inputClass}
                    />
                </label>
                {#if form?.error}
                    <p class="text-sm text-error">{form.error}</p>
                {/if}
                <button type="submit" class={cn(btnPrimaryClass, "w-full")}>
                    Code anfordern
                </button>
            </form>
        {:else}
            <div class="flex flex-col gap-4">
                <form
                    method="POST"
                    action="?/verifyCode"
                    class="flex flex-col gap-4 items-center"
                >
                    <p class="text-subtle text-sm">
                        Code wurde an <span class="text-base font-medium"
                            >{email}</span
                        > gesendet.
                    </p>
                    <label class="flex flex-col gap-1.5">
                        <span class="text-sm font-medium">Code</span>

                        <PinInput.Root
                            class="group/pininput text-base flex items-center"
                            name="code"
                            maxlength={6}
                            pattern={REGEXP_ONLY_DIGITS}
                        >
                            {#snippet children({ cells })}
                                <div class="flex">
                                    {#each cells as cell}
                                        {@render Cell(cell)}
                                    {/each}
                                </div>
                            {/snippet}
                        </PinInput.Root>
                        {#snippet Cell(cell: CellProps)}
                            <PinInput.Cell
                                {cell}
                                class={cn(
                                    pinCellClass,
                                    "flex items-center justify-center transition-all duration-75",
                                    "group-focus-within/pininput:border-input group-hover/pininput:border-input",
                                    "outline-0 data-active:ring-2 data-active:ring-focus",
                                )}
                            >
                                {#if cell.char !== null}
                                    <div>
                                        {cell.char}
                                    </div>
                                {/if}
                                {#if cell.hasFakeCaret}
                                    <div
                                        class="animate-caret-blink pointer-events-none absolute inset-0 flex items-center justify-center"
                                    >
                                        <div
                                            class="h-8 w-px bg-base-inverted"
                                        ></div>
                                    </div>
                                {/if}
                            </PinInput.Cell>
                        {/snippet}
                    </label>

                    <label class="flex items-center gap-2 text-sm">
                        <Checkbox.Root
                            name="rememberMe"
                            checked={form?.rememberMe}
                            class={checkboxClass}
                        >
                            {#snippet children({ checked })}
                                {#if checked}
                                    <CheckIcon size="16" class="text-white" />
                                {/if}
                            {/snippet}
                        </Checkbox.Root>
                        Angemeldet bleiben
                    </label>
                    {#if form?.error}
                        <p class="text-sm text-error">{form.error}</p>
                    {/if}
                    <div class="flex flex-col w-full">
                        <button type="submit" class={btnPrimaryClass}>
                            Einloggen
                        </button>
                    </div>
                </form>
                <form method="post" action="?/startOver">
                    <button type="submit" class={cn(btnSecondaryClass, "w-full")}>
                        Andere E-Mail verwenden
                    </button>
                </form>
            </div>
        {/if}
    </div>
</div>

// apps/web/src/routes/login.tsx
import { createFileRoute, redirect, useRouter } from "@tanstack/react-router";
import { Button } from "@tipprunde/ui";
import { ArrowLeftIcon, CheckIcon } from "lucide-react";
import { useState, useTransition } from "react";
import {
  CheckboxButton,
  CheckboxField,
  FieldError,
  Form,
  Input,
  Label,
  TextField,
} from "react-aria-components";

import { getPendingLogin, requestCode, startOver, verifyCode } from "#/lib/auth.ts";
import type { LoginStep } from "#/lib/auth.ts";

export const Route = createFileRoute("/login")({
  beforeLoad: ({ context }) => {
    if (context.user) {
      throw redirect({ to: "/" });
    }
  },
  loader: () => getPendingLogin(),
  component: RouteComponent,
});

const fieldClasses = "flex flex-col gap-1.5";
const labelClasses = "text-app text-sm font-medium";
const inputClasses =
  "border-subtle bg-surface text-app focus-visible:ring-accent rounded-sm border px-3 py-2 text-sm outline-none transition ease-out focus-visible:ring-2";

function RouteComponent() {
  const router = useRouter();
  const initial = Route.useLoaderData();

  const [state, setState] = useState<LoginStep>(initial);
  const [email, setEmail] = useState(initial.email ?? "");
  const [code, setCode] = useState("");
  const [rememberMe, setRememberMe] = useState(false);
  const [pending, startTransition] = useTransition();

  function submitEmail(e: React.FormEvent) {
    e.preventDefault();
    startTransition(async () => {
      const result = await requestCode({ data: { email } });
      setCode("");
      setState(result);
    });
  }

  function submitCode(e: React.FormEvent) {
    e.preventDefault();
    startTransition(async () => {
      const result = await verifyCode({ data: { code, rememberMe } });
      if (result.done) {
        // Cookie is set on the response; refresh session context, then leave /login.
        await router.invalidate();
        await router.navigate({ to: "/" });
        return;
      }
      setState(result);
    });
  }

  function changeEmail() {
    startTransition(async () => {
      await startOver();
      setCode("");
      setState({ step: "email", email });
    });
  }

  return (
    <div className="mx-auto flex w-full max-w-sm flex-col px-4 py-12">
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-semibold tracking-tight">Anmelden</h1>
        <p className="text-subtle mt-1 text-sm">
          {state.step === "email"
            ? "Melde dich mit deiner E-Mail-Adresse an."
            : `Wir haben einen Code an ${state.email} gesendet.`}
        </p>
      </div>

      <div className="border-subtle bg-surface-raised shadow-popover rounded-md border p-6">
        {state.step === "email" ? (
          <Form onSubmit={submitEmail} className="flex flex-col gap-4">
            <TextField name="email" type="email" isRequired className={fieldClasses}>
              <Label className={labelClasses}>E-Mail</Label>
              <Input
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="email"
                autoFocus
                className={inputClasses}
              />
              <FieldError className="text-error text-sm" />
            </TextField>

            {state.error && <p className="text-error text-sm">{state.error}</p>}

            <Button type="submit" isDisabled={pending} className="mt-1">
              {pending ? "Sende Code …" : "Code anfordern"}
            </Button>
          </Form>
        ) : (
          <Form onSubmit={submitCode} className="flex flex-col gap-4">
            <TextField name="code" isRequired className={fieldClasses}>
              <Label className={labelClasses}>Login-Code</Label>
              <Input
                value={code}
                onChange={(e) => setCode(e.target.value)}
                inputMode="numeric"
                autoComplete="one-time-code"
                maxLength={6}
                placeholder="123456"
                autoFocus
                className={`${inputClasses} text-center text-lg tracking-[0.5em]`}
              />
              <FieldError className="text-error text-sm" />
            </TextField>

            <CheckboxField
              isSelected={rememberMe}
              onChange={setRememberMe}
              className="flex items-center gap-2 text-sm"
            >
              <CheckboxButton className="group border-subtle data-selected:border-accent data-selected:bg-accent data-focused:ring-accent flex size-5 items-center justify-center rounded border transition ease-out outline-none data-focused:ring-2">
                <CheckIcon className="group-data-selected:text-accent-fg size-3 stroke-[3] text-transparent" />
              </CheckboxButton>
              <Label className="text-app select-none">Angemeldet bleiben</Label>
            </CheckboxField>

            {state.error && <p className="text-error text-sm">{state.error}</p>}

            <Button type="submit" isDisabled={pending} className="mt-1">
              {pending ? "Prüfe Code …" : "Anmelden"}
            </Button>

            <Button
              type="button"
              intent="ghost"
              size="sm"
              isDisabled={pending}
              onPress={changeEmail}
              className="self-center"
            >
              <ArrowLeftIcon className="size-4" />
              Andere E-Mail
            </Button>
          </Form>
        )}
      </div>
    </div>
  );
}
