// src/routes/_front/tabelle.tsx
import { createFileRoute } from "@tanstack/react-router";

import { fetchCurrentChampionshipFn } from "#/app/front/championships.ts";
import { fetchRankingFn } from "#/app/front/ranking.ts";

export const Route = createFileRoute("/_front/tabelle")({
  loader: async () => {
    const championship = await fetchCurrentChampionshipFn();
    if (!championship) return { championship: null, ranking: [] };
    const ranking = await fetchRankingFn({ data: championship.id });
    return { championship, ranking };
  },
  head: ({ loaderData }) => ({
    meta: [
      { title: loaderData?.championship ? `Tabelle | ${loaderData.championship.name}` : "Tabelle" },
    ],
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const { championship, ranking } = Route.useLoaderData();

  if (!championship) {
    return (
      <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col items-center justify-center gap-2 py-24 text-center">
        <p className="text-subtle text-sm">Noch kein aktives Turnier.</p>
      </div>
    );
  }

  return (
    <div className="xs:px-4 mx-auto w-full max-w-5xl py-8">
      <div className="xs:px-0 mb-6 flex flex-col gap-1 px-4">
        <h1 className="text-2xl font-semibold tracking-tight">{championship.name}</h1>
        <p className="text-subtle text-sm">
          {championship.completed ? "Abschlusstabelle" : "Aktuelle Tabelle"}
        </p>
      </div>
      <div className="bg-surface border-surface xs:rounded-md xs:border border-y px-4 py-2">
        <table className="w-full text-base">
          <thead>
            <tr className="border-input border-b text-left">
              <th className="text-subtle w-px px-2 pt-2 pb-3 text-right text-xs font-medium tracking-wide uppercase">
                Platz
              </th>
              <th className="text-subtle px-2 pt-2 pb-3 text-left text-xs font-medium tracking-wide uppercase">
                Spieler
              </th>
              <th className="text-subtle w-px px-2 pt-2 pb-3 text-center text-xs font-medium tracking-wide uppercase">
                Punkte
              </th>
            </tr>
          </thead>
          <tbody>
            {ranking.length === 0 ? (
              <tr>
                <td colSpan={3} className="text-subtle px-2 py-6 text-center">
                  Noch keine Tipps gewertet.
                </td>
              </tr>
            ) : (
              ranking.map((entry, index) => (
                <tr key={entry.userId} className="border-input border-b last:border-b-0">
                  <td className="w-px px-2 py-3 text-right tabular-nums">
                    {index === 0 || ranking[index - 1].rank !== entry.rank ? entry.rank : ""}
                  </td>
                  <td className="px-2 py-3 text-left">{entry.name}</td>
                  <td className="px-2 py-3 text-center font-medium tabular-nums">{entry.points}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// apps/web/src/routes/tabelle/+page.svelte
<script lang="ts">
    import type { PageProps } from "./$types";

    const { data }: PageProps = $props();
</script>

<svelte:head>
    <title>Tabelle · {data.championship.name}</title>
</svelte:head>

<div class="mx-auto w-full max-w-5xl py-8">
    <div class="xs:px-0 mb-6 flex flex-col items-center gap-2 px-4">
        <h1 class="text-2xl font-semibold tracking-tight">
            {data.championship.name}
        </h1>
        <div class="flex items-center gap-4 text-sm">
            <span class="font-medium">
                {data.championship.completed
                    ? "Abschlusstabelle"
                    : "Aktuelle Tabelle"}</span
            >
            <a
                href="/verlauf"
                class="text-subtle hover:text-base focus-visible:ring-focus rounded transition-colors outline-none focus-visible:ring-2 focus-visible:ring-offset-4 focus-visible:ring-offset-base"
            >
                Punkteverlauf
            </a>
        </div>
    </div>
    <div
        class="xs:mx-4 bg-surface border-surface xs:rounded-md xs:border border-y px-2 xs:px-4 py-2"
    >
        <table class="w-full text-sm">
            <thead>
                <tr class="border-input border-b text-left">
                    <th
                        class="text-subtle w-px px-2 pt-2 pb-3 text-right text-xs font-medium tracking-wide uppercase"
                    >
                        Platz
                    </th>
                    <th
                        class="text-subtle px-2 pt-2 pb-3 text-left text-xs font-medium tracking-wide uppercase"
                    >
                        Spieler
                    </th>
                    <th
                        class="text-subtle w-px px-2 pt-2 pb-3 text-center text-xs font-medium tracking-wide uppercase"
                    >
                        Punkte
                    </th>
                </tr>
            </thead>
            <tbody>
                {#each data.ranking as entry, index}
                    <tr class="border-input border-b last:border-b-0">
                        <td class="w-px px-2 py-3 text-right tabular-nums">
                            {entry.rank !== data.ranking[index - 1]?.rank
                                ? entry.rank
                                : ""}
                        </td>
                        <td class="px-2 py-3 text-left">
                            <a
                                href={`/spieler/${entry.slug}`}
                                class={`${data.user?.id === entry.userId ? "text-accent" : "text-subtle hover:text-base"} focus-visible:ring-focus rounded font-medium transition-colors outline-none focus-visible:ring-2 focus-visible:ring-offset-4 focus-visible:ring-offset-surface`}
                            >
                                {entry.name}
                            </a>
                        </td>
                        <td
                            class="px-2 py-3 text-center font-medium tabular-nums"
                            >{entry.points}</td
                        >
                    </tr>
                {/each}
            </tbody>
        </table>
    </div>
</div>
