// apps/web/src/routes/verlauf/+page.svelte
<script lang="ts">
    import { LineChart } from "layerchart";

    import type { PageProps } from "./$types";

    const { data }: PageProps = $props();

    const COLORS = [
        "oklch(65% 0.20 45)",
        "oklch(60% 0.22 240)",
        "oklch(55% 0.20 145)",
        "oklch(60% 0.20 300)",
        "oklch(62% 0.22 20)",
        "oklch(65% 0.20 195)",
        "oklch(68% 0.18 65)",
        "oklch(60% 0.20 320)",
        "oklch(60% 0.20 265)",
        "oklch(60% 0.20 170)",
        "oklch(65% 0.20 85)",
        "oklch(55% 0.20 10)",
    ];

    const series = $derived(data.players.map((p, i) => ({
        key: `u${p.userId}`,
        label: p.name,
        value: `u${p.userId}`,
        color: COLORS[i % COLORS.length],
    })));
</script>

<div class="mx-auto w-full max-w-5xl py-8">
    <div class="xs:px-0 mb-6 flex flex-col items-center gap-2 px-4">
        <h1 class="text-2xl font-semibold tracking-tight">
            {data.championship.name}
        </h1>
        <div class="flex items-center gap-4 text-sm">
            <a
                href="/tabelle"
                class="text-subtle hover:text-base focus-visible:ring-focus rounded transition-colors outline-none focus-visible:ring-2 focus-visible:ring-offset-4 focus-visible:ring-offset-base"
            >
                {data.championship.completed
                    ? "Abschlusstabelle"
                    : "Aktuelle Tabelle"}
            </a>
            <span class="font-medium">Punkteverlauf</span>
        </div>
    </div>

    {#if data.chartData.length === 0}
        <div
            class="xs:mx-4 bg-surface border-surface xs:rounded-md xs:border flex items-center justify-center border-y py-16 text-sm text-subtle"
        >
            Noch keine Ergebnisse
        </div>
    {:else}
        <div
            class="xs:mx-4 bg-surface border-surface xs:rounded-md xs:border h-[480px] border-y p-4"
            style="--color-surface-100: var(--background-color-surface); --color-surface-content: var(--text-color-base); --color-primary: var(--background-color-accent)"
        >
            <LineChart
                data={data.chartData}
                x="matchNr"
                {series}
                legend={true}
                padding={{ top: 8, right: 8, bottom: 32, left: 48 }}
            />
        </div>
    {/if}
</div>

// src/routes/_front/verlauf.tsx
import { Link, createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { inArray } from "drizzle-orm";

import { PunkteverlaufChart } from "#/components/punkteverlauf-chart.tsx";
import { computeRanking } from "#/domain/ranking.ts";
import { db } from "#db";
import { getLatestPublishedChampionship } from "#db/dal/championships.ts";
import { getPlayers } from "#db/dal/players.ts";
import { tips } from "#db/schema/tables.ts";

const fetchVerlaufFn = createServerFn({ method: "GET" }).handler(async () => {
  const championship = await getLatestPublishedChampionship();
  if (!championship) return null;

  const allPlayers = await getPlayers(championship.id);

  const roundIds = (
    await db.query.rounds.findMany({
      where: { championshipId: championship.id, published: true },
      columns: { id: true },
    })
  ).map((r) => r.id);

  const allMatches =
    roundIds.length > 0
      ? await db.query.matches.findMany({
          where: { roundId: { in: roundIds }, result: { isNotNull: true } },
          columns: { id: true, nr: true },
          orderBy: { nr: "asc" },
        })
      : [];

  const matchIds = allMatches.map((m) => m.id);

  const allTips =
    matchIds.length > 0
      ? await db
          .select({ matchId: tips.matchId, userId: tips.userId, points: tips.points })
          .from(tips)
          .where(inArray(tips.matchId, matchIds))
      : [];

  const players = allPlayers.map((p) => ({
    userId: p.userId,
    name: p.user?.name ?? "",
  }));

  // Accumulate points match by match and snapshot ranking after each
  const cumulative = new Map<number, number>(players.map((p) => [p.userId, 0]));

  const snapshots = allMatches.map((match) => {
    allTips
      .filter((t) => t.matchId === match.id)
      .forEach((t) => {
        cumulative.set(t.userId, (cumulative.get(t.userId) ?? 0) + (t.points ?? 0));
      });

    const ranked = computeRanking(
      players.map((p) => ({ userId: p.userId, points: cumulative.get(p.userId) ?? 0 })),
    );

    return {
      matchNr: match.nr,
      entries: ranked.map((r) => ({ userId: r.userId, points: r.points, rank: r.rank })),
    };
  });

  // Sort players by final ranking
  const finalSnapshot = snapshots.at(-1);
  const sortedPlayers = [...players].sort((a, b) => {
    const ra = finalSnapshot?.entries.find((e) => e.userId === a.userId)?.rank ?? 999;
    const rb = finalSnapshot?.entries.find((e) => e.userId === b.userId)?.rank ?? 999;
    return ra - rb;
  });

  return {
    championshipName: championship.name,
    completed: championship.completed,
    sortedPlayers,
    snapshots,
  };
});

export const Route = createFileRoute("/_front/verlauf")({
  loader: () => fetchVerlaufFn(),
  component: VerlaufComponent,
});

function VerlaufComponent() {
  const data = Route.useLoaderData();

  if (!data) return <p className="p-4">Kein aktives Turnier.</p>;

  const { championshipName, completed, sortedPlayers, snapshots } = data;
  const tabelleLabel = completed ? "Abschlusstabelle" : "Aktuelle Tabelle";

  return (
    <div className="xs:px-4 mx-auto w-full max-w-5xl py-8">
      <div className="xs:px-0 mb-6 flex flex-col gap-2 px-4">
        <h1 className="text-2xl font-semibold tracking-tight">{championshipName}</h1>
        <div className="flex items-center gap-4 text-sm">
          <Link
            to="/tabelle"
            className="focus-visible:ring-focus text-subtle hover:text-foreground rounded transition-colors outline-none focus-visible:ring-2 focus-visible:ring-offset-2"
          >
            {tabelleLabel}
          </Link>
          <span className="font-medium">Punkteverlauf</span>
        </div>
      </div>
      <PunkteverlaufChart players={sortedPlayers} snapshots={snapshots} />
    </div>
  );
}
